### ISSUE TITLE
.vimディレクトリをなんとかする

### ISSUE THREAD

**Issue by skyriser** [skyriser/dotfiles#1]
基本的には ftplugin ディレクトリに各々のインデントなりを記述していく方式にしたいのだけど、.vimが `init.sh` の対象外になってるのでアレい。

NeoBundleをsubmodule化するなりして.vimもsymlinkで運用できる形に変更する。

**Comment by skyriser** [comment]
割と綺麗にしましたよ。 :muscle:

**Comment by blueberrystream** [comment]
:+1:
